---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/

patches:
  - target:
      kind: DataProtectionApplication
      name: oadp-dpa-hml
    patch: |-
      - op: replace
        path: /spec/backupLocations/0/velero/config/s3Url
        value: "http://s3.hml.com.br"

  - target:
      kind: Schedule
      name: backup-completo-12h
    patch: |-
      - op: replace
        path: /metadata/name
        value: "backup-completo-24h"
      - op: replace
        path: /spec/schedule
        value: "0 */24 * * *"
