---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/

patches:
  - target:
      kind: DataProtectionApplication
      name: oadp-dpa-des
    patch: |-
      - op: replace
        path: /spec/backupLocations/0/velero/config/s3Url
        value: "http://s3.des.com.br"

  - target:
      kind: Schedule
      name: backup-completo-12h
    patch: |-
      - op: replace
        path: /metadata/name
        value: "backup-completo-48h"
      - op: replace
        path: /spec/schedule
        value: "0 */48 * * *"

  # - target:
  #     group: operators.coreos.com
  #     version: v1alpha1
  #     kind: Subscription
  #     name: redhat-oadp-operator
  #     namespace: openshift-adp
  #   patch: |-
  #     - op: replace
  #       path: /spec/channel
  #       value: 'stable-1.1'

