argocd: 
  namespace: openshift-gitops

project:
  name: appsets
  description: Appsets Projects
  sourceRepos:
    - https://github.com/ederqueirozdf/ocp-catalog.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc

applications:

  - name: app-oadp
    repoURL: https://github.com/ederqueirozdf/ocp-catalog.git
    path: appset-oadp
    destinationNamespace: default
    destinationServer: https://kubernetes.default.svc

